# Generated by Django 3.2.4 on 2021-07-30 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='num_stars',
            field=models.IntegerField(choices=[(1, 'Worst'), (2, 'Bad'), (3, 'Meh'), (4, 'Good'), (5, 'Very Good')]),
        ),
    ]
